const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.CSV,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{TiledBackground: 0},
	{"3DCamera": 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{Jumpthru: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Solid: 0},
	{Sprite5: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{TiledBackground6: 0},
	{Sprite9: 0},
	{bronze: 0},
	{tombol1: 0},
	{Keyboard: 0},
	{Audio: 0},
	{AJAX: 0},
	{Array: 0},
	{CSV: 0},
	{Score: 0},
	{ButtonSubmit: 0},
	{TextNama: 0},
	{TextKelas: 0},
	{Text: 0},
	{Anchor: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{"1A": 0},
	{"1B": 0},
	{"1C": 0},
	{"1D": 0},
	{"1AB": 0},
	{"2BB": 0},
	{"2CB": 0},
	{"2DB": 0},
	{Mouse: 0},
	{tombol5: 0},
	{Move: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Soal9: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{tombol2: 0},
	{Rotate: 0},
	{Sprite13: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sine: 0},
	{Sprite17: 0},
	{Sprite33: 0},
	{box3: 0},
	{Box4: 0},
	{Soal2: 0},
	{True: 0},
	{Soal2A: 0},
	{Soal2B: 0},
	{Soal2C: 0},
	{Soal2D: 0},
	{Browser: 0},
	{Sound: 0},
	{TombolNext: 0},
	{Point: 0},
	{soal1: 0},
	{PG: 0},
	{Jawabanbenar: 0},
	{Jawabansalah: 0},
	{Enemy: 0},
	{tekansoal: 0},
	{PG2: 0},
	{Jawabanbenar2: 0},
	{SheetCode: 0},
	{JawabanPG2: 0},
	{JumlahpilihJawabanSoal2: 0},
	{Coin: 0},
	{S: 0},
	{WebAppURL: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	_3DCamera: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	bronze: class extends self.ISpriteInstance {},
	tombol1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	CSV: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	ButtonSubmit: class extends self.IButtonInstance {},
	TextNama: class extends self.ITextInputInstance {},
	TextKelas: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	_1A: class extends self.ISpriteInstance {},
	_1B: class extends self.ISpriteInstance {},
	_1C: class extends self.ISpriteInstance {},
	_1D: class extends self.ISpriteInstance {},
	_1AB: class extends self.ISpriteInstance {},
	_2BB: class extends self.ISpriteInstance {},
	_2CB: class extends self.ISpriteInstance {},
	_2DB: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	tombol5: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Soal9: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	tombol2: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	box3: class extends self.ISpriteInstance {},
	Box4: class extends self.ISpriteInstance {},
	Soal2: class extends self.ISpriteInstance {},
	Soal2A: class extends self.ISpriteInstance {},
	Soal2B: class extends self.ISpriteInstance {},
	Soal2C: class extends self.ISpriteInstance {},
	Soal2D: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sound: class extends self.ISpriteInstance {},
	TombolNext: class extends self.ISpriteInstance {},
	Point: class extends self.ISpriteInstance {},
	soal1: class extends self.ISpriteInstance {},
	PG: class extends self.ISpriteInstance {},
	Jawabanbenar: class extends self.ISpriteInstance {},
	Jawabansalah: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	tekansoal: class extends self.ISpriteInstance {},
	PG2: class extends self.ISpriteInstance {},
	Jawabanbenar2: class extends self.ISpriteInstance {}
}